language: java
jdk:
- openjdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
after_success:
- mvn clean test jacoco:report coveralls:report
deploy:
  provider: heroku
  app: openbooks-api
  on: feature/implement-double-entry-system
  api_key:
    secure: oyaZJngPMTWiBxKX8kdBAKItoYYC2rX7jriJgRaTOk9P8C2mpufA8+1BYrDeSWTl13dCYICEneCrKQ2Z1ypjgrAc2ObXd4nI6u1YBkFb8U3CsfD0YP9TpQVMK9lHnWo1/lrWisHFkE/l0WDbRQO9JBQ+vRXTGt2CmT0YXvT8v4G7wnekYA6ZlxgRaqDItpVYWP1L9UDWR+10dIQvFZlxGx1w43JhxzpaD48roRChYSgoXXgCxqoHYnMxujAdNlmH+uf07K2nPTuG4EncF2sAYOU56uNxTnUHkuAgpaGZYH8i+glGMMUfx6226i1DlnI541TWfyJM7c3RZTyArkgfeCZWXTrrvtqRRcq0g2KUCrmHZVr5k8Wr95P/SOmIXNautVf4yNNHxJ2KWFEY02YVtJ9A8H4G4/AxWVv4W4I0fGSVsOom0iYuBkDWr75Uf4V94Iko85M4jyZR7lrUDEUb+8BKHxcuVcBQJv9VcMdHraJWSGZXm3HFBgERcIFySCakoMIR4VU96xXmfbxqzilO2gzQwM+7bj+Zie77gC65D0mSXt2f56FxVHTkclsyI0tbNbxCMYJHPO4TvRex4RK9CFUmL6+EQGMrEXXCa+DFsRUuE0srDp6JZRYXhaWa1SsAU9gTBTjRu1oDGGUc91R78Q332D5Bh7KfFG2Kpu8/EK0=
