language: java
jdk:
 - openjdk8
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
after_success:
  - mvn clean test jacoco:report coveralls:report
deploy:
  provider: heroku
  app: openbooks-api
  on: "feature/implement-double-entry-system"
  api_key:
    secure: "aCLYnXmk2a7YrpTkPXcfY+z7UWOMXaqOU02DORekdaRT1ixR4mqQjOKNud2O36HgdW/S5Cpk5agHnTrEs3MRxXdiaY30dVfEV+8Vqd1biXsYgASp7MQaDl0e/h5pq6vfxB/2FSri8QU6weaN2xa5TKeCE+XZ2+Hjz+yRvj7NHMpGKUwkNwKlVrYP7VIg67vBW8hwLHeWiRgJFkpYgG24rv+uHkeUJdbMdZRlHIsuoIj7/ymK/ivzd3FNslQfxgNcJZ+HXKr006EWb6Q4ipta/6AB4I25SysSh3m/0poyAq+33mezXeO5WTXbgTLJNFsrjSObcSO4Wf+gNKvyY5oBnE1DZLXSRTmnM39Gq9L8gD1JAqnss/qzMNpF/sn5njnhoXB1z3dROS1ibMXfkazwKRxz2dTjbXFGxCz7FhBWLOaS57sQ2oYTadjsWeJOzBlhyVhha47KN4iUbn61OPLdTDaTffjTKLyNx7VBo+oKhfGLPkyJCCKELI0RVFPOa+uEAuWw0H7pafZSavkKwuwSkQYXB7usQg00Qlg5pwu0sgP++5X5M0z+/QJywfvKqlnG/KYDO8O1faTHmtiilKkHY5s0ZX+ca3TB784590WJ1VLrx69zbXDsdWmFM5uOWQgonRFoeN9c2zFag79W1x76bI/76UXbk6b4qpq/zxvr+H0="
