openbooks:
  persistenceProvider: "INMEMORY"
  bookkeepingMethod: "DOUBLE_ENTRY"
  
logging:
  level:
    root: "INFO"
    
spring:
  jpa:
    open-in-view: "false"
  profiles:
    active: "dev"
    
---

spring:
  profiles: "dev"
  environment: "development"
  h2:
    # JDBC url: jdbc:h2:mem:testdb
    console:
      enabled: "true"
      path: "/h2-console"
  jpa:
    # enable ddl generation
#    generate-ddl: "false"
    hibernate:
      ddl-auto: "none"
     # create a file containing SQL schema, blocks hibernate ddl
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: "metadata"
#            scripts:
#              action: "create"
#              create-target: "create.sql"
    show-sql: "false"
      
---

spring:
  profiles: "prod"
  environment: "production"
  jpa:
    generate-ddl: "false"
    hibernate:
      ddl-auto: "none"